name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch: # allows you to run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generates the snake animation from your contribution graph
      - uses: Platane/snk@v3
        with:
          github_user_name: YOUR_USERNAME
          outputs: dist/snake.svg

      # Push the generated snake.svg file to a new branch called "output"
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
